package com.mycompany.java_project;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
 /*
*
 * @author ASUS
 */

public class ProgramManagerPanel extends javax.swing.JFrame {
    private Member currentMember; 
    private String chosenDate;
    private File_Manager fm = new File_Manager();

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProgramManagerPanel.class.getName());
    /**
     * Creates new form ProgramManagerPanel
     */
    public ProgramManagerPanel(Member member) {
    this.currentMember = member;
    initComponents();
    this.setLocationRelativeTo(null);
    
    restrictComboBoxByPlan();
    
    jComboBox1.addActionListener(e -> updateTrainerTable());
    updateTrainerTable();
}
   private void restrictComboBoxByPlan() {
    jComboBox1.removeAllItems();
    
    if (currentMember != null && currentMember.getMembershipPlan() != null) {
        String planName = currentMember.getMembershipPlan().name(); // FITNESS, FITNESS_PILATES vb.
        
        System.out.println("DEBUG: Member Plan Name -> " + planName);

        switch (planName) {
            case "FITNESS":
                jComboBox1.addItem("Fitness");
                break; 
                
            case "FITNESS_PILATES":
                jComboBox1.addItem("Fitness");
                jComboBox1.addItem("Pilates");
                break; 
                
            case "FITNESS_SWIMMING_PILATES":
                jComboBox1.addItem("Fitness");
                jComboBox1.addItem("Swim");
                jComboBox1.addItem("Pilates");
                break; 
                
            default:
                jComboBox1.addItem("Fitness");
                break;
        }
    } else {
        jComboBox1.addItem("Fitness");
    }
}

private void updateTrainerTable() {
        try {
            String selectedBranch = jComboBox1.getSelectedItem().toString();
            List<User> allUsers = fm.readUsers("users.json");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); 
            for (User u : allUsers) {
                if (u instanceof Trainer t && t.getBranch().equalsIgnoreCase(selectedBranch)) {
                    model.addRow(new Object[]{t.getName() + " " + t.getSurname(), false, false, false, false});
                }
            }
        } catch(Exception e) { }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        textField1 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textField1.setBackground(new java.awt.Color(153, 0, 255));
        textField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField1.setForeground(new java.awt.Color(255, 255, 255));
        textField1.setText("Schedule Panel");

        jLabel1.setText("Exercise Type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fitness", "Swim", "Pilates" }));

        jButton1.setText("Tarih seç");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Trainer", "08.00-10.00", "10.00-12.00", "13.00-15.00", "15.00-17.00"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jButton2.setText("Save");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String input = JOptionPane.showInputDialog(this, "Tarih girin (GG.AA.YYYY):");
        if (input != null && !input.isEmpty()) {
            try {
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd.MM.yyyy");
                LocalDate selectedDate = LocalDate.parse(input, dtf);
                if (!selectedDate.isBefore(LocalDate.now()) && !selectedDate.isAfter(LocalDate.now().plusDays(7))) {
                    chosenDate = input;
                    jButton1.setText(chosenDate);
                }
            } catch (Exception e) { }
        
    }    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int selectedRow = jTable1.getSelectedRow();
    int selectedCol = jTable1.getSelectedColumn();

    if (chosenDate == null) {
        JOptionPane.showMessageDialog(this, "Lütfen önce bir tarih seçin!");
        return;
    }
    if (selectedRow == -1 || selectedCol < 1) {
        JOptionPane.showMessageDialog(this, "Lütfen tablodan bir hoca ve saat dilimi seçin!");
        return;
    }

    String trainerName = jTable1.getValueAt(selectedRow, 0).toString();
    String timeSlot = jTable1.getColumnName(selectedCol);

    List<User> allUsers = fm.readUsers("users.json");
    boolean isBusy = false;

    for (User u : allUsers) {
        if (u instanceof Member m) {
            if (m.getAssignedTrainer() != null &&
                m.getAssignedTrainer().equals(trainerName) &&
                m.getAssignedDate().equals(chosenDate) &&
                m.getAssignedTimeSlot().equals(timeSlot)) {
                
                isBusy = true;
                break;
            }
        }
    }

    if (isBusy) {
        JOptionPane.showMessageDialog(this, "Seçtiğiniz saatte " + trainerName + " doludur. Lütfen başka bir saat veya hoca seçin.");
    } else {
        currentMember.setAssignedTrainer(trainerName);
        currentMember.setAssignedDate(chosenDate);
        currentMember.setAssignedTimeSlot(timeSlot);
        
        allUsers.removeIf(u -> u.getID().equals(currentMember.getID()));
        allUsers.add(currentMember);
        fm.writeAllUsers("users.json", allUsers);
        
        JOptionPane.showMessageDialog(this, "Randevunuz başarıyla alındı!");
        
        new UserMainPanel(currentMember).setVisible(true);
        this.dispose();
    }    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> new ProgramManagerPanel(new Member()).setVisible(true));
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}