package com.mycompany.java_project;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class UserMainPanel extends javax.swing.JFrame {
    private Member currentMember; // Üyeyi hafızada tutalım

    public UserMainPanel(Member member) {
        this.currentMember = member; // Giriş yapan üyeyi aldık
        initComponents();
        displayUserInfo();
    }
    
    private void displayUserInfo() {
        if (currentMember != null) {
        // 1. Üyelik Planını Göster
        if (currentMember.getMembershipPlan() != null) {
            jTextField3.setText(currentMember.getMembershipPlan().getPlanName());
        }
        jTextField3.setEditable(false);

        // 2. Tarihleri Göster
        String startDate = currentMember.getStartDate() != null ? currentMember.getStartDate().toString() : "Girilmedi";
        String endDate = currentMember.getEndDate() != null ? currentMember.getEndDate().toString() : "Girilmedi";
        jTextField4.setText(startDate + " / " + endDate);
        jTextField4.setEditable(false);

        // 3. Kalan Gün
        long remainingDays = currentMember.checkMembershipStatus();
        if (remainingDays > 0) {
            jTextArea2.setText("Hoşgeldin " + currentMember.getName() + "!\n"
                    + "Üyeliğinin bitmesine " + remainingDays + " gün kaldı.");
        } else {
            jTextArea2.setText("Üyeliğinizin süresi dolmuş veya son günü.");
        }

        // 4. Tabloyu Doldur (Randevu Detayları)
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // Temizle
        
        if (currentMember.getAssignedTrainer() != null) {
            // Tarih ve saat bilgisini birleştirerek tabloya ekliyoruz
            String scheduleInfo = (currentMember.getAssignedDate() != null ? currentMember.getAssignedDate() : "") 
                                 + " " + (currentMember.getAssignedTimeSlot() != null ? currentMember.getAssignedTimeSlot() : "");
            
            model.addRow(new Object[]{
                currentMember.getAssignedTrainer(), 
                "Egzersiz", 
                scheduleInfo, 
                "Sil"
            });
        }
    }
          
    }
    
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserMainPanel.class.getName());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        textField4 = new java.awt.TextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        button3 = new java.awt.Button();

        textField1.setText("textField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Atanan bir eğitmen veya pogram bulunmamaktadır.");
        jScrollPane5.setViewportView(jTextArea2);

        jTextField3.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jTextField3.setText("ÜYELİK TİPİ");

        textField4.setBackground(new java.awt.Color(153, 0, 255));
        textField4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textField4.setForeground(new java.awt.Color(255, 255, 255));
        textField4.setText("USER MAİN");

        jTextField4.setText("Üyelik başlangıç-Bitiş Tarihi");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Trainer Name", "Exercise Type", "Hours", "Delete"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable2);

        button3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        button3.setLabel("Add Program");
        button3.addActionListener(this::button3ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        jScrollPane4.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
   new ProgramManagerPanel(currentMember).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_button3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
             int column = jTable2.columnAtPoint(evt.getPoint()); 
    int row = jTable2.rowAtPoint(evt.getPoint());    

    if (column == 3 && row != -1) {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Mevcut programınızı ve eğitmeninizi silmek istediğinize emin misiniz?", 
            "Programı Sil", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            removeAssignedProgram(); // Silme işlemini yapan metot
        }
    }
    }//GEN-LAST:event_jTable2MouseClicked

    private void removeAssignedProgram() {
   try {
        // Tüm randevu bilgilerini temizle
        currentMember.setAssignedTrainer(null);
        currentMember.setAssignedDate(null);
        currentMember.setAssignedTimeSlot(null);

        // JSON dosyasını güncelle
        File_Manager fm = new File_Manager();
        java.util.List<User> allUsers = fm.readUsers("users.json");
        allUsers.removeIf(u -> u.getID().equals(currentMember.getID()));
        allUsers.add(currentMember);
        fm.writeAllUsers("users.json", allUsers);

        // Arayüzü yenile
        displayUserInfo();
        javax.swing.JOptionPane.showMessageDialog(this, "Program başarıyla kaldırıldı.");
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Hata: " + e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
        new UserMainPanel(new Member()).setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private java.awt.TextField textField1;
    private java.awt.TextField textField4;
    // End of variables declaration//GEN-END:variables
}
